# Generated by Django 4.2.30 on 2026-05-12 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('task', 'やること'), ('buy', '買うもの'), ('research', '調べる'), ('contact', '連絡'), ('idea', 'アイデア'), ('worry', '不安'), ('other', 'その他')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低'), ('unset', '未設定')], default='unset', max_length=20)),
                ('status', models.CharField(choices=[('inbox', '未整理'), ('today', '今日やる'), ('week', '今週やる'), ('someday', 'いつか'), ('done', '完了'), ('trash', '捨てる')], default='inbox', max_length=20)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'reminder_at', '-created_at'],
            },
        ),
    ]
