# Generated by Django 4.2.30 on 2026-05-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memo',
            name='google_event_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='google_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
