# Generated by Django 4.2.30 on 2026-07-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_googlecalendarcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
